-- migrate:up

INSERT INTO ejercicios (id, nombre, imagen, cuerpo_parte_id) VALUES(1, 'Flexión de pecho', 'flexion_pecho.jpg', 1);
INSERT INTO ejercicios (id, nombre, imagen, cuerpo_parte_id) VALUES(2, 'Press de banca', 'press_banca.jpg', 1);
INSERT INTO ejercicios (id, nombre, imagen, cuerpo_parte_id) VALUES(3, 'Fondos', 'fondos.jpg', 1);
INSERT INTO ejercicios (id, nombre, imagen, cuerpo_parte_id) VALUES(4, 'Aperturas', 'aperturas.jpg', 1);
INSERT INTO ejercicios (id, nombre, imagen, cuerpo_parte_id) VALUES(5, 'Pull-over', 'pull_over.jpg', 2);
INSERT INTO ejercicios (id, nombre, imagen, cuerpo_parte_id) VALUES(6, 'Dominadas', 'dominadas.jpg', 2);
INSERT INTO ejercicios (id, nombre, imagen, cuerpo_parte_id) VALUES(7, 'Remo con barra', 'remo_barra.jpg', 2);
INSERT INTO ejercicios (id, nombre, imagen, cuerpo_parte_id) VALUES(8, 'Jalón al pecho', 'jalon_pecho.jpg', 2);
INSERT INTO ejercicios (id, nombre, imagen, cuerpo_parte_id) VALUES(9, 'Elevaciones frontales', 'elevaciones_frontales.jpg', 3);
INSERT INTO ejercicios (id, nombre, imagen, cuerpo_parte_id) VALUES(10, 'Press militar', 'press_militar.jpg', 3);
INSERT INTO ejercicios (id, nombre, imagen, cuerpo_parte_id) VALUES(11, 'Pájaros', 'pajaros.jpg', 3);
INSERT INTO ejercicios (id, nombre, imagen, cuerpo_parte_id) VALUES(12, 'Remo vertical', 'remo_vertical.jpg', 3);
INSERT INTO ejercicios (id, nombre, imagen, cuerpo_parte_id) VALUES(13, 'Curl de bíceps con barra', 'curl_biceps_barra.jpg', 4);
INSERT INTO ejercicios (id, nombre, imagen, cuerpo_parte_id) VALUES(14, 'Curl martillo', 'curl_martillo.jpg', 4);
INSERT INTO ejercicios (id, nombre, imagen, cuerpo_parte_id) VALUES(15, 'Curl concentrado', 'curl_concentrado.jpg', 4);
INSERT INTO ejercicios (id, nombre, imagen, cuerpo_parte_id) VALUES(16, 'Curl en banco inclinado', 'curl_banco_inclinado.jpg', 4);
INSERT INTO ejercicios (id, nombre, imagen, cuerpo_parte_id) VALUES(17, 'Fondos entre bancos', 'fondos_bancos.jpg', 5);
INSERT INTO ejercicios (id, nombre, imagen, cuerpo_parte_id) VALUES(18, 'Press de triceps en polea', 'press_triceps_polea.jpg', 5);
INSERT INTO ejercicios (id, nombre, imagen, cuerpo_parte_id) VALUES(19, 'Extensiones de triceps', 'extensiones_triceps.jpg', 5);
INSERT INTO ejercicios (id, nombre, imagen, cuerpo_parte_id) VALUES(20, 'Rompecráneos', 'rompecerebros.jpg', 5);
INSERT INTO ejercicios (id, nombre, imagen, cuerpo_parte_id) VALUES(21, 'Crunch', 'crunch.jpg', 6);
INSERT INTO ejercicios (id, nombre, imagen, cuerpo_parte_id) VALUES(22, 'Plancha', 'plancha.jpg', 6);
INSERT INTO ejercicios (id, nombre, imagen, cuerpo_parte_id) VALUES(23, 'Elevación de piernas', 'elevacion_piernas.jpg', 6);
INSERT INTO ejercicios (id, nombre, imagen, cuerpo_parte_id) VALUES(24, 'Ab twist', 'ab_twist.jpg', 6);
INSERT INTO ejercicios (id, nombre, imagen, cuerpo_parte_id) VALUES(25, 'Sentadillas', 'sentadillas.jpg', 8);
INSERT INTO ejercicios (id, nombre, imagen, cuerpo_parte_id) VALUES(26, 'Prensa', 'prensa.jpg', 8);
INSERT INTO ejercicios (id, nombre, imagen, cuerpo_parte_id) VALUES(27, 'Lunges', 'lunges.jpg', 8);
INSERT INTO ejercicios (id, nombre, imagen, cuerpo_parte_id) VALUES(28, 'Extensiones de pierna', 'extensiones_pierna.jpg', 8);
INSERT INTO ejercicios (id, nombre, imagen, cuerpo_parte_id) VALUES(29, 'Peso muerto', 'peso_muerto.jpg', 9);
INSERT INTO ejercicios (id, nombre, imagen, cuerpo_parte_id) VALUES(30, 'Curl femoral', 'curl_femoral.jpg', 9);
INSERT INTO ejercicios (id, nombre, imagen, cuerpo_parte_id) VALUES(31, 'Buenos días', 'buenos_dias.jpg', 9);
INSERT INTO ejercicios (id, nombre, imagen, cuerpo_parte_id) VALUES(32, 'Prensa de piernas', 'prensa_piernas.jpg', 9);
INSERT INTO ejercicios (id, nombre, imagen, cuerpo_parte_id) VALUES(33, 'Elevación de talones', 'elevacion_talones.jpg', 10);
INSERT INTO ejercicios (id, nombre, imagen, cuerpo_parte_id) VALUES(34, 'Gemelos en máquina', 'gemelos_maquina.jpg', 10);
INSERT INTO ejercicios (id, nombre, imagen, cuerpo_parte_id) VALUES(35, 'Saltos de talón', 'saltos_talon.jpg', 10);
INSERT INTO ejercicios (id, nombre, imagen, cuerpo_parte_id) VALUES(36, 'Elevaciones de talones de pie', 'elevaciones_pie.jpg', 10);
INSERT INTO ejercicios (id, nombre, imagen, cuerpo_parte_id) VALUES(37, 'Elevación de cadera', 'elevacion_cadera.jpg', 7);
INSERT INTO ejercicios (id, nombre, imagen, cuerpo_parte_id) VALUES(38, 'Puente de glúteos', 'puente_gluteos.jpg', 7);
INSERT INTO ejercicios (id, nombre, imagen, cuerpo_parte_id) VALUES(39, 'Patadas de glúteo', 'patadas_gluteo.jpg', 7);
INSERT INTO ejercicios (id, nombre, imagen, cuerpo_parte_id) VALUES(40, 'Sentadillas sumo', 'sentadillas_sumo.jpg', 7);
INSERT INTO ejercicios (id, nombre, imagen, cuerpo_parte_id) VALUES(41, 'Curl de antebrazos', 'curl_antebrazos.jpg', 12);
INSERT INTO ejercicios (id, nombre, imagen, cuerpo_parte_id) VALUES(42, 'Extensiones de muñeca', 'extensiones_muneca.jpg', 12);
INSERT INTO ejercicios (id, nombre, imagen, cuerpo_parte_id) VALUES(43, 'Flexión de muñeca', 'flexion_muneca.jpg', 12);
INSERT INTO ejercicios (id, nombre, imagen, cuerpo_parte_id) VALUES(44, 'Curl inverso', 'curl_inverso.jpg', 12);
INSERT INTO ejercicios (id, nombre, imagen, cuerpo_parte_id) VALUES(45, 'Flexiones', 'flexiones.jpg', 1);
INSERT INTO ejercicios (id, nombre, imagen, cuerpo_parte_id) VALUES(46, 'Press con mancuernas', 'press_mancuernas.jpg', 1);
INSERT INTO ejercicios (id, nombre, imagen, cuerpo_parte_id) VALUES(47, 'Flexión de brazos en banco', 'flexion_banco.jpg', 1);
INSERT INTO ejercicios (id, nombre, imagen, cuerpo_parte_id) VALUES(48, 'Jalón en polea alta', 'jalon_polea_alta.jpg', 2);
INSERT INTO ejercicios (id, nombre, imagen, cuerpo_parte_id) VALUES(49, 'Remo con mancuerna', 'remo_mancuerna.jpg', 2);
INSERT INTO ejercicios (id, nombre, imagen, cuerpo_parte_id) VALUES(50, 'Curl de bíceps con mancuernas', 'curl_biceps_mancuerna.jpg', 4);
INSERT INTO ejercicios (id, nombre, imagen, cuerpo_parte_id) VALUES(51, 'Curl de bíceps en banco', 'curl_biceps_banco.jpg', 4);
INSERT INTO ejercicios (id, nombre, imagen, cuerpo_parte_id) VALUES(52, 'Press de triceps en banco', 'press_triceps_banco.jpg', 5);
INSERT INTO ejercicios (id, nombre, imagen, cuerpo_parte_id) VALUES(53, 'Patada de glúteo', 'patada_gluteo.jpg', 7);
INSERT INTO ejercicios (id, nombre, imagen, cuerpo_parte_id) VALUES(54, 'Crunch invertido', 'crunch_invertido.jpg', 6);
INSERT INTO ejercicios (id, nombre, imagen, cuerpo_parte_id) VALUES(55, 'Prensa de piernas en máquina', 'prensa_piernas_maquina.jpg', 8);
INSERT INTO ejercicios (id, nombre, imagen, cuerpo_parte_id) VALUES(56, 'Elevación de talones en máquina', 'elevacion_talones_maquina.jpg', 10);
INSERT INTO ejercicios (id, nombre, imagen, cuerpo_parte_id) VALUES(57, 'Zancadas', 'zancadas.jpg', 8);
INSERT INTO ejercicios (id, nombre, imagen, cuerpo_parte_id) VALUES(58, 'Elevación de rodillas', 'elevacion_rodillas.jpg', 6);
INSERT INTO ejercicios (id, nombre, imagen, cuerpo_parte_id) VALUES(59, 'Peso muerto rumano', 'peso_muerto_rumano.jpg', 9);
INSERT INTO ejercicios (id, nombre, imagen, cuerpo_parte_id) VALUES(60, 'Sentadilla frontal', 'sentadilla_frontal.jpg', 8);
INSERT INTO ejercicios (id, nombre, imagen, cuerpo_parte_id) VALUES(61, 'Press de hombros', 'press_hombros.jpg', 3);
INSERT INTO ejercicios (id, nombre, imagen, cuerpo_parte_id) VALUES(62, 'Elevación lateral', 'elevacion_lateral.jpg', 3);
INSERT INTO ejercicios (id, nombre, imagen, cuerpo_parte_id) VALUES(63, 'Push press', 'push_press.jpg', 3);
INSERT INTO ejercicios (id, nombre, imagen, cuerpo_parte_id) VALUES(64, 'Triceps en cuerda', 'triceps_cuerda.jpg', 5);
INSERT INTO ejercicios (id, nombre, imagen, cuerpo_parte_id) VALUES(65, 'Curl de piernas', 'curl_piernas.jpg', 9);
INSERT INTO ejercicios (id, nombre, imagen, cuerpo_parte_id) VALUES(66, 'Lunges con mancuernas', 'lunges_mancuernas.jpg', 8);
INSERT INTO ejercicios (id, nombre, imagen, cuerpo_parte_id) VALUES(67, 'Peso muerto convencional', 'peso_muerto_convencional.jpg', 9);
INSERT INTO ejercicios (id, nombre, imagen, cuerpo_parte_id) VALUES(68, 'Sentadilla Hack', 'sentadilla_hack.jpg', 8);

-- migrate:down

DELETE FROM ejercicios;